name: Spell Checker 2

on: [pull_request]

jobs:
  spell_checking:
    name: LanguageTool
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Review dog languagetool
        id: "review"
        uses: reviewdog/action-languagetool@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: "github-pr-check"
          # Change reporter level if you need.
          level: "error"
          patterns: "**/*.md **/*.txt **/*.mdx"
          #enabled_categories: 'STYLE,PLAIN_ENGLISH,WHITESPACE_RULE,EN_QUOTES,DASH_RULE,WORD_CONTAINS_UNDERSCORE,UPPERCASE_SENTENCE_START,ARROWS,COMMA_PARENTHESIS_WHITESPACE,UNLIKELY_OPENING_PUNCTUATION,SENTENCE_WHITESPACE,EN_UNPAIRED_BRACKETS,PHRASE_REPETITION,PUNCTUATION_PARAGRAPH_END'
          disabled_categories: ""
          disabled_rules: ""

      - name: Check for error annotations
        run: |
          echo $GITHUB_WORKSPACE
          # Check if error annotations exist and fail the step if so
          if grep -q '::error' $GITHUB_WORKSPACE; then
            echo "Error annotations found!"
            exit 1
          fi

      - name: Continue with other steps
        run: echo "No errors detected in the previous step."
